### ISSUE TITLE
Allow Custom Posters

### ISSUE THREAD

**Issue by jaruba** [jaruba/rpdb-features#1]
This seems to be the most requested feature so far.

Given that this requires significantly more resources then the other features, it can only be added to Tier 3.

**Comment by RobinMM** [comment]
custom posters is nice for finetuning in some cases, but I would prefer textless/TMDB posters over this feature.

**Comment by jaruba** [comment]
That feature is requested here: https://github.com/jaruba/rpdb-features/issues/3

TBH, I would try to add both, but custom posters will require much more resources then TMDB / textless posters IMO, which is why it might only be possible to add it to Tier 3, while TMDB / textless might make it to Tier 2.

I can't, in good conscious, add more features to Tier 1, as that has been made to be the cheapest with minimum profit, most of it goes to various taxes and service payments, the other Tiers have a bit more wiggle space.
